### ISSUE TITLE
Mosaic install but doesn't run

### ISSUE THREAD

**Issue by lukechilds** [mistydemeo/homebrew-formulae#5]
Tried to install Mosaic which compiled surprisingly fast:

```
$ brew install mistydemeo/formulae/mosaic-ck
==> Tapping mistydemeo/formulae
Cloning into '/usr/local/Library/Taps/mistydemeo/homebrew-formulae'...
remote: Counting objects: 24, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 24 (delta 0), reused 13 (delta 0), pack-reused 0
Unpacking objects: 100% (24/24), done.
Checking connectivity... done.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/aview.rb:6:in `<class:Aview>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/aview.rb:6:in `<class:Aview>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/aview.rb:6:in `<class:Aview>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/darktable.rb:7:in `<class:Darktable>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/darktable.rb:7:in `<class:Darktable>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/darktable.rb:7:in `<class:Darktable>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/gopher.rb:6:in `<class:Gopher>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/gopher.rb:6:in `<class:Gopher>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/gopher.rb:6:in `<class:Gopher>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/org2xm.rb:7:in `<class:Org2xm>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/org2xm.rb:7:in `<class:Org2xm>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/org2xm.rb:7:in `<class:Org2xm>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/sfnt2woff.rb:6:in `<class:Sfnt2woff>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/sfnt2woff.rb:6:in `<class:Sfnt2woff>'
Please report this to the mistydemeo/formulae tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/mistydemeo/homebrew-formulae/sfnt2woff.rb:6:in `<class:Sfnt2woff>'
Please report this to the mistydemeo/formulae tap!

Tapped 21 formulae (67 files, 56.9K)
==> Installing mosaic-ck from mistydemeo/formulae
==> Installing dependencies for mistydemeo/formulae/mosaic-ck: libpng, freetype, fontconfig, homebrew/x11/openmotif
==> Installing mistydemeo/formulae/mosaic-ck dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.24.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libpng-1.6.24.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.24: 26 files, 1.2M
==> Installing mistydemeo/formulae/mosaic-ck dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.6.5.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring freetype-2.6.5.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.6.5: 61 files, 2.5M
==> Installing mistydemeo/formulae/mosaic-ck dependency: fontconfig
==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.12.1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring fontconfig-2.12.1.el_capitan.bottle.tar.gz
==> Using the sandbox
==> Regenerating font cache, this may take a while
==> /usr/local/Cellar/fontconfig/2.12.1/bin/fc-cache -frv
🍺  /usr/local/Cellar/fontconfig/2.12.1: 468 files, 3M
==> Installing mistydemeo/formulae/mosaic-ck dependency: homebrew/x11/openmotif
==> Downloading https://homebrew.bintray.com/bottles-x11/openmotif-2.3.4.el_capitan.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring openmotif-2.3.4.el_capitan.bottle.2.tar.gz
🍺  /usr/local/Cellar/openmotif/2.3.4: 1,274 files, 15.7M
==> Installing mistydemeo/formulae/mosaic-ck
==> Downloading http://www.floodgap.com/retrotech/machten/mosaic/mosaic27ck10.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/mistydemeo/mosaic-ck/commit/32eb14ee8d65616c953e965c6a8b1d754eedc7a0.diff
######################################################################## 100.0%
==> Downloading https://github.com/duckinator/mosaic-ck/commit/ffbb7ad9166da3f5d3524d63fb30469ba12c85e6.diff
######################################################################## 100.0%
==> Patching
==> Applying 32eb14ee8d65616c953e965c6a8b1d754eedc7a0.diff
patching file src/readPNG.c
==> Applying ffbb7ad9166da3f5d3524d63fb30469ba12c85e6.diff
patching file libwww2/HTMIME.c
==> make osx
🍺  /usr/local/Cellar/mosaic-ck/2.7-10ck: 5 files, 1.2M, built in 50 seconds
```

However when I try and run Mosaic I get:

```
$ Mosaic
dyld: Library not loaded: /opt/X11/lib/libXt.7.dylib
  Referenced from: /usr/local/opt/openmotif/lib/libXm.4.dylib
  Reason: image not found
zsh: trace trap  Mosaic
```

Do I need to install some other dependency manually? I have XQuartz.

**Comment by lukechilds** [comment]
Hmmn, updating XQuartz resolved the above issue. However now I'm getting:

```
$ Mosaic
Error: Couldn't find per display information
```

Any ideas @mistydemeo?

**Comment by mistydemeo** [comment]
Hm, I'm getting a different error:

```
mosaic                                                  master
Created ~/.mosaic (and ~/Library/Mosaic-CK where supported)

Congratulations, you have found a bug in
NCSA Mosaic 2.7ck10 on Mac OS X.

If a core file was generated in your directory,
please do one of the following:

  % dbx /path/to/Mosaic /path/to/core
  dbx> where

OR

  % gdb /path/to/Mosaic /path/to/core
  gdb> where

Mail the results, and a description of what you were doing at the time,
(include any URLs involved!) to ckaiser@floodgap.com.

We thank you for your support.

...exiting NCSA Mosaic now.

fish: 'mosaic' terminated by signal SIGABRT (Abort)
```

**Comment by mistydemeo** [comment]
Here's the backtrace from the core dump:

```
* thread #1: tid = 0x169124, 0x000000010025113a libXm.4.dylib`_XmAddHashEntry + 26, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
  * frame #0: 0x000000010025113a libXm.4.dylib`_XmAddHashEntry + 26
    frame #1: 0x000000010024bf52 libXm.4.dylib`XmeTraitSet + 68
    frame #2: 0x00000001001aaa03 libXm.4.dylib`ClassPartInitialize + 43
    frame #3: 0x00000001003b24f5 libXt.7.dylib`XtInitializeWidgetClass + 578
    frame #4: 0x00000001003b3493 libXt.7.dylib`xtWidgetAlloc + 95
    frame #5: 0x00000001003b284e libXt.7.dylib`xtCreate + 124
    frame #6: 0x00000001003b2f63 libXt.7.dylib`_XtCreatePopupShell + 251
    frame #7: 0x00000001003de1b6 libXt.7.dylib`XtVaCreatePopupShell + 346
    frame #8: 0x000000010000ab89 mosaic`mo_do_gui + 1735
    frame #9: 0x000000010000469e mosaic`main + 141
    frame #10: 0x00007fff9ea015ad libdyld.dylib`start + 1
```

**Comment by lukechilds** [comment]
Hey, thanks for getting back to me. Unfortunately that doesn't mean a lot to me :(

Seems like it may still be something to do with X11/XQuartz.
